package unalcol.optimization.operators;

import unalcol.optimization.generation.RepairProvider;
import unalcol.types.collection.vector.*;

/**
 * <p>Title:ArityTwo</p>
 * <p>Description: A binary operator </p>
 * <p>Copyright:    Copyright (c) 2010</p>
 * @author Jonatan Gomez
 * @version 1.0
 */

public abstract class ArityTwo<G> extends Operator<G> {

  /**
   * Apply the binary genetic operator over the individual
   * @param one First individual to be modified by the genetic operator
   * @param two Second individual to be modified by the genetic operator
   * @return extra information of the genetic operator
   */
  public abstract Vector<G> generates(G one, G two);

  /**
   * Apply the unary genetic operator over the individual
   * @param obj Individual to be modified by the genetic operator
   * @return extra information of the genetic operator
   */
  public Vector<G> applies(G one, G two){
      Vector<G> pop = generates(one, two);
      for( int i=0; i<pop.size(); i++ ){
        pop.set( i, (G)RepairProvider.repair(pop.get(i)) );          
      }
      return pop;
  }

  
  /**
   * Apply the genetic operator to the first and second individuals in the population of parents
   * This method is parent compatible
   * @param parents Collection of parents used by the genetic operator (selects just the first and second
   * individuals in the collection
   * @return A collection of individuals generated by the gentic operator
   */
  @Override
  public Vector<G> generates( Vector<G> parents ){
      return generates( parents.get(0), parents.get(1) );
  }

  /**
   * Return the genetic operator arity
   * @return the genetic operator arity
   */
  public int getArity() { return 2; }

}
